import assert from "node:assert/strict";
import { test } from "node:test";
import { generateExample } from "../src/generate-example.js";

test("generates a safe example file without secret values", () => {
  const result = generateExample("PORT=3000\nDATABASE_URL=postgres://localhost/app\nSESSION_SECRET=abcdefghi\nFEATURE=true\n");

  assert.equal(result.errors.length, 0);
  assert.equal(result.content, `# Generated by EnvShape CLI.
# Keep real secrets in .env and commit only safe placeholders here.
PORT=3000
DATABASE_URL=
SESSION_SECRET=
FEATURE=
`);
});

test("can keep safe literals when requested", () => {
  const result = generateExample("FEATURE=true\nWORKERS=2\n", { keepDefaults: true });

  assert.match(result.content, /FEATURE=true/);
  assert.match(result.content, /WORKERS=2/);
});
