import { entriesByKey, parseEnv } from "./env-parser.js";

const SAFE_DEFAULT_KEYS = new Set([
  "NODE_ENV",
  "APP_ENV",
  "PORT",
  "HOST",
  "LOG_LEVEL"
]);

const SECRET_KEY_PATTERN = /(secret|token|password|passwd|private|credential|api[_-]?key|access[_-]?key|database_url|db_url)/i;

export function generateExample(content, options = {}) {
  const source = options.source ?? ".env";
  const keepDefaults = Boolean(options.keepDefaults);
  const parsed = parseEnv(content, source);
  const index = entriesByKey(parsed.entries);
  const lines = [
    "# Generated by EnvShape CLI.",
    "# Keep real secrets in .env and commit only safe placeholders here."
  ];

  for (const entry of index.map.values()) {
    lines.push(`${entry.key}=${safeExampleValue(entry, keepDefaults)}`);
  }

  return {
    content: `${lines.join("\n")}\n`,
    errors: parsed.errors,
    duplicates: index.duplicates
  };
}

function safeExampleValue(entry, keepDefaults) {
  if (SECRET_KEY_PATTERN.test(entry.key)) {
    return "";
  }

  if (SAFE_DEFAULT_KEYS.has(entry.key)) {
    return entry.value;
  }

  if (keepDefaults && looksSafeLiteral(entry.value)) {
    return entry.value;
  }

  return "";
}

function looksSafeLiteral(value) {
  const trimmed = value.trim();

  if (trimmed === "") {
    return true;
  }

  if (/^(true|false)$/i.test(trimmed)) {
    return true;
  }

  if (/^\d+$/.test(trimmed)) {
    return true;
  }

  if (/^[A-Za-z0-9_,.-]+$/.test(trimmed) && trimmed.length <= 32) {
    return true;
  }

  return false;
}
